options:
  port:
    type: string
    default: RANDOM
    description: The port to bind on the host or RANDOM to pick a random port
  docker-image:
    type: string
    default: katharostech-com
    description: >
      The name of the docker image to use. This must be the name of the tag for the docker
      image that is uploaded in the "docker-image" resource

